# Generated by Django 4.1 on 2024-04-13 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_tests', '0002_alter_productpictures_options_productpictures_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='template_name',
            field=models.CharField(default='default_quiz_template.html', max_length=100),
        ),
    ]
